#!/bin/bash

DOMAIN=$1
CLEAN_DOMAIN=$(echo "$DOMAIN" | tr -cd '[:alnum:].-')
FOLDER="recon-$CLEAN_DOMAIN"
REPORT="$FOLDER/report.html"

mkdir -p "$FOLDER"

cat <<EOF > "$REPORT"
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Recon Report - $CLEAN_DOMAIN</title>
  <style>
    body {
      font-family: 'Segoe UI', sans-serif;
      background: #1c1c1c;
      color: #f2f2f2;
      margin: 0;
      padding: 30px;
    }
    h1 {
      color: #00ffff;
      text-align: center;
      font-size: 36px;
      margin-bottom: 40px;
    }
    .section {
      margin-bottom: 30px;
      border: 1px solid #444;
      border-radius: 8px;
      overflow: hidden;
      background: #2a2a2a;
    }
    .section summary {
      background: #333;
      padding: 15px 20px;
      font-size: 20px;
      cursor: pointer;
    }
    pre {
      padding: 15px 20px;
      background: #222;
      color: #dcdcdc;
      white-space: pre-wrap;
      overflow-x: auto;
      margin: 0;
    }
    footer {
      margin-top: 40px;
      text-align: center;
      font-size: 14px;
      color: #888;
    }
  </style>
</head>
<body>
  <h1>🔍 Recon Report for $CLEAN_DOMAIN</h1>
EOF

add_section() {
  echo "<details class='section'><summary>$1</summary><pre>${2:-No data found}</pre></details>" >> "$REPORT"
}

# Check for necessary tools
for cmd in dig whois traceroute curl; do
  if ! command -v $cmd &> /dev/null; then
    add_section "Missing Tool: $cmd" "$cmd is required but not installed."
  fi
done

IP_ADDRESS=$(dig +short "$DOMAIN" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n 1)
add_section "IP Address of Domain" "$IP_ADDRESS"

WHOIS_RESULT=$(whois "$DOMAIN" 2>/dev/null | head -n 50)
add_section "WHOIS Information" "$WHOIS_RESULT"

DNS_RESULT=$(dig "$DOMAIN" ANY +noall +answer 2>/dev/null)
add_section "DNS Records (dig)" "$DNS_RESULT"

TRACEROUTE_RESULT=$(traceroute "$DOMAIN" 2>/dev/null)
add_section "Traceroute Output" "$TRACEROUTE_RESULT"

# Try HTTPS first, fallback to HTTP
HTTP_HEADERS=$(curl -I --max-time 10 "https://$DOMAIN" 2>&1)
if [[ "$HTTP_HEADERS" == *"Failed"* ]]; then
  HTTP_HEADERS=$(curl -I --max-time 10 "http://$DOMAIN" 2>&1)
fi
add_section "HTTP Headers" "$HTTP_HEADERS"

# crt.sh subdomains
CRT_RESULT=$(curl -s "https://crt.sh/?q=%25.$DOMAIN&output=json" | grep -oP '"common_name":"\K[^"]+')
UNIQUE_SUBS=$(echo "$CRT_RESULT" | sort -u | head -n 20)
add_section "Subdomains via crt.sh" "$UNIQUE_SUBS"

cat <<EOF >> "$REPORT"
<footer>Generated by <strong>MyRecon</strong> | Linux Shell Web Recon Toolkit</footer>
</body>
</html>
EOF
